---
- name: Configure common things
  hosts: slave
  tags: 
    - prepare
  user: root
#  sudo: yes
  roles:
    - roles/common

- name: Configure slave node
  hosts: slave
  user: root
  tags: 
    - slave
  vars: 
    master_host: "{{groups['master'][0]}}"
#  sudo: yes
  roles:
    - roles/slave

