---
#- name: Install redis ruby gem for redis-trib.rb
#  gem: name=redis state=latest

#- name: Create initialization script
#  template: src=initialize_cluster.j2 dest=/root/initialize_cluster.sh

#- name: Initialize cluster
#  shell: bash /root/initialize_cluster.sh

- name: Create initialization script
  template: src=startredis.j2 dest=/root/startredis.sh

- name: Place the redis.conf file on all hosts
  template: src=redis.conf.j2 dest=/etc/redis.conf

- name: Start redis
  service: name=redis-server state=started
#  shell: bash /root/startredis.sh
